create schema pass_param;
set search_path=pass_param;
create table pass_param.foo ( a int, b int);
create table pass_param.bar( c int, d int);
create index foo_idx on pass_param.foo using btree(b);
insert into pass_param.foo values (1,1),(1,2),(1,5);
insert into pass_param.bar values (1,1);
insert into pass_param.bar select i,i from generate_series(3,10)i;
analyze pass_param.foo;
analyze pass_param.bar;
set enable_hashjoin to off;
set enable_mergejoin to off;
set enable_seqscan to off;
set enable_material to off;
set enable_bitmapscan to off;
set enable_nestloop to on;
set enable_indexscan to on;
set gp_vmem_idle_resource_timeout to 100000;
explain select b from foo,bar where foo.b = bar.c;
select b from foo,bar where foo.b = bar.c;
